
before:
  hooks:
  - ./bin/packr2
builds:
- env:
  - CGO_ENABLED=0
- flags:
  - -mod=vendor
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    amd64: 64-bit
  vendor: Pascal Dennerly
  homepage: https://github.com/dnnrly/abbreviate/
  maintainer: Pascal Dennerly <dnnrly@gmail.com>
  description: Shorten your strings using common abbreviations.
  license: Apache 2.0
  formats:
    - rpm
