
before:
  hooks:
builds:
- env:
  - CGO_ENABLED=0
- goos:
  - linux
  - darwin
  - windows
  goarch:
  - amd64
archive:
  replacements:
    darwin: Darwin
    linux: Linux
    windows: Windows
    amd64: x86_64
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
nfpm:
  name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
  replacements:
    amd64: 64-bit
    386: 32-bit
    darwin: macOS
    linux: Tux
  vendor: Pascal Dennerly
  homepage: https://github.com/dnnrly/abbreviate/
  maintainer: Pascal Dennerly <dnnrly@gmail.com>
  description: Shorten your strings using common abbreviations.
  license: Apache 2.0
  formats:
    - deb
    - rpm
