name: github pages

on:
  push:
    branches:
    - master
    paths:
    - 'docs/**'
    - '.github/workflows/gh-pages.yml'

jobs:
  build-deploy:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@master

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.2.1
      with:
        hugo-version: '0.58.3'

    - name: Prepare Themes
      run: |
        git submodule sync && git submodule update --init

    - name: Disable Jekyll
      run: mkdir -p ./docs/public && touch ./docs/public/.nojekyll

    - name: Build
      run: cd docs && hugo -t learn -d public --gc --minify --cleanDestinationDir

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v2.4.0
      with:
        emptyCommits: false
      env:
        ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
        PUBLISH_BRANCH: gh-pages
        PUBLISH_DIR: ./docs/public
