name: Validate for PR
on: push
jobs:
    validate:
        name: Validate abbreviate
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-go@v1
              with:
                go-version: '1.12'
              #            - uses/scripts/action
            - run: make ci-test deps build acceptance-test
