name: Validate for PR
on: push
jobs:
    validate:
        name: Validate abbreviate
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@master
            - uses: ./scripts/action
            - run: find / -name packr2 && make PACKR_BIN=packr2 ci-test build acceptance-test
