name: Release workflow
#on:
#  push:
#    tags:
#      - 'v*'
on: push
jobs:
  validate:
    name: Validate abbreviate
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - run: make test
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ validate ]
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: goreleaser
      uses: docker://goreleaser/goreleaser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release --snapshot
      if: success()
