name: Release workflow
#on:
#  push:
#    tags:
#      - 'v*'
on: push
jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    needs: [ validate ]
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: goreleaser
      uses: docker://goreleaser/goreleaser
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        args: release --snapshot
      if: success()
